### ISSUE TITLE
Download in Specific Folder

### ISSUE THREAD

**Issue by suthagarmca** [vasani-arpit/cordova-plugin-downloadmanager#6]

**Comment by vasani-arpit** [comment]
Need to check if Android supports that or not.

**Comment by mrl0w53c** [comment]
where the speficic folder? i already download a picture.. when i see in my gallery the picture is not showing... and i check in download folder.. the file is missing or not in download folder

**Comment by vasani-arpit** [comment]
@mrl0w53c 
Right now file goes to Downloads folder on the phone. If download succeeds file should be there.

**Comment by mrl0w53c** [comment]
@vasani-arpit
Oh I found it ... but the location is : phone storage > android > data > com.app.xxx > file > downloads > myfile.jpg

i am using android marsmellow, and when i download using browser , the fill will in the default location like : phone storage > download > myfile.jpg

can i configuration the location of download folder to default download folder...?

because this location : phone storage > android > data > com.app.xxx > file > downloads > myfile.jpg
the picture cant detected in my gallery...
Thank You :)

and sorry if my english is bad :D

**Comment by vasani-arpit** [comment]
Yes, we are planning to provide this feature.

**Comment by mrl0w53c** [comment]
@vasani-arpit
Ok.. i will wait..  this plugin is so simple to use it..

did u configure the download location to app data?

**Comment by vasani-arpit** [comment]
No, I didn't. I think android automatically set it to that folder.

**Comment by mrl0w53c** [comment]
Ok bro.. i will wait .. hope fast u add the feature to this plugin 😁
